/* 登录 */
export const LOGIN_IN_SUCCESS = 'LOGIN_IN_SUCCESS';
/* 登出 */
export const LOGOUT_IN_SUCCESS = 'LOGOUT_IN_SUCCESS';
/* 获取用户信息 */
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';

export const BIND_USER_PHONE_SUCCESS = 'BIND_USER_PHONE_SUCCESS';

/* 获取列表成功 */
export const GET_OFFER_LIST_SUCCESS = 'GET_OFFER_LIST_SUCCESS';
export const GET_PUBLIC_LIST_SUCCESS = 'GET_PUBLIC_LIST_SUCCESS';
export const GET_INVOLVED_LIST_SUCCESS = 'GET_INVOLVED_LIST_SUCCESS';
export const GET_ALL_LIST_SUCCESS = 'GET_ALL_LIST_SUCCESS';

export const CLEAR_ALL_LISTS = 'CLEAR_ALL_LISTS';

export const GET_LIST_CHANGE_AJAX_STATE = 'GET_LIST_CHANGE_AJAX_STATE';
/* 获取数量统计接口 */
export const GET_ORDER_STATISTIC_SUCCESS = 'GET_ORDER_STATISTIC_SUCCESS';

/* 获取报价单详情 */
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS'
export const SET_ORDER_DETAIL_SIZE_TABLE = 'SET_ORDER_DETAIL_SIZE_TABLE'
/* 获取简单报价历史 */
export const GET_SIMPLE_OFFER_DETAIL_SUCEESS = 'GET_SIMPLE_OFFER_DETAIL_SUCEESS'
export const SUBMIT_SIMPLE_OFFER_PRICE = 'SUBMIT_SIMPLE_OFFER_PRICE';
/* 复杂报价 */
export const GET_COMPLEX_OFFER_SUCCESS = 'GET_COMPLEX_OFFER_SUCCESS';
export const SUBMIT_COMPLEX_OFFER_PRICE = 'SUBMIT_COMPLEX_OFFER_PRICE';

export const SET_COMPLEX_OFFER_FABRIC = 'SET_COMPLEX_OFFER_FABRIC';
export const SET_COMPLEX_OFFER_ACCESSORIES = 'SET_COMPLEX_OFFER_ACCESSORIES';
export const SET_COMPLEX_OFFER_OTHER = 'SET_COMPLEX_OFFER_OTHER';

export const SAVE_COMPLEX_OFFER = 'SAVE_COMPLEX_OFFER'

/* 设置title */
export const SET_TITLE = 'SET_TITLE'
/* 注册 */
export const SIGN_UP = 'SIGN_UP'
/* 修改信息 */
export const EDIT_USER_INFO = 'EDIT_USER_INFO'
/* 获取首页数据 */
export const SET_HOME_DATA = 'GET_HOME_DATA'
/** 设置提示语 */
export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE'
/* 获取测试数据 */
export const GET_TEST_DATA = 'GET_TEST_DATA'
